//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maps.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [Serializable]
    public partial class Character
    {
        [DisplayName("Character Identifier")]
        public int Character_ID { get; set; }

        [DisplayName("Player")]
        [Required]
        public int Player_ID { get; set; }

        [Required]
        public string Name { get; set; }

        [DisplayName("Avatar")]
        public string Avatar_IMG { get; set; }

        public virtual Player Player { get; set; }
    }
}
