//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.Encounter_Character = new HashSet<Encounter_Character>();
        }
    
        public int Character_ID { get; set; }
        public int Player_ID { get; set; }
        public string Name { get; set; }
        public string Avatar_IMG { get; set; }
        public short Initative_Bonus { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual ICollection<Encounter_Character> Encounter_Character { get; set; }
    }
}
