//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encounter_Monster
    {
        public int Encounter_ID { get; set; }
        public int Monster_ID { get; set; }
        public short Initiative { get; set; }
    
        public virtual Encounter Encounter { get; set; }
        public virtual Monster Monster { get; set; }
    }
}
