//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int Map_ID { get; set; }
        public string Name { get; set; }
        public string Background_IMG_Path { get; set; }
        public int Width_Squares { get; set; }
        public int Height_Squares { get; set; }
        public int SortOrder { get; set; }
        public bool Active { get; set; }
    }
}
